### ISSUE TITLE
Publish new release for godot3 that includes "Enclose directories in command with double-quote"

### ISSUE THREAD

**Issue by mizutani256** [imjp94/gd-plug#17]
Probably surrounding the `dest` path on `_GitExecutable.clone()` with quotes should fix it.

**Comment by mizutani256** [comment]
My bad, I should have checked the version I was using. I'm on tag 0.1.1 because we use Godot 3, but I see that the branch for Godot 3 also has the fix already. Sorry for that.

In which case, I guess what I actually need is a new release for Godot 3. I can open a new issue for that and close this one.

I know we could just use the Godot 3 branch but we prefer having dependencies with stable versions and we are not in a hurry since this problem is not breaking anything right now.

**Comment by imjp94** [comment]
I see, we can just rename this issue.
I will make a new release 0.1.2, after I port some fix from `master`

**Comment by imjp94** [comment]
Just released [0.1.2](https://github.com/imjp94/gd-plug/releases/tag/0.1.2)
