### ISSUE TITLE
Nice Plugin

### ISSUE THREAD

**Issue by paulhocker** [imjp94/gd-plug#2]
Not really an issue, but a comment. This is a really nice plugin, and is similar to my tool gs-project-manager

https://gitlab.com/godot-stuff/gs-project-manager

I really like the integration with Godot.

**Comment by imjp94** [comment]
Thanks!

Wow, that's a very cool project, and definitely a more powerful one, while gd-plug only cares about dependencies.

(Closing this issue, feel free to open a [Discussion](https://github.com/imjp94/gd-plug/discussions) if you have other comments)
