### ISSUE TITLE
add an example for using releases instead of a repo

### ISSUE THREAD

**Issue by yankscally** [imjp94/gd-plug#35]
using `plug("godot-jolt/godot-jolt")` doesn't work, as it is the GDExtension source code.

**Comment by yankscally** [comment]
its in a zip here... any ideas?

https://github.com/godot-jolt/godot-jolt/releases/download/v0.13.0-stable/godot-jolt_v0.13.0-stable.zip

**Comment by imjp94** [comment]
No, installing compiled binaries from github release is not supported, see #26 

Closing as duplicate of #26
